# Form implementation generated from reading ui file 'D:\Study\DoAnPython\formDangNhap.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_formDangNhap(object):
    def setupUi(self, formDangNhap):
        formDangNhap.setObjectName("formDangNhap")
        formDangNhap.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(parent=formDangNhap)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitleDN = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitleDN.setGeometry(QtCore.QRect(140, 30, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.lblTitleDN.setFont(font)
        self.lblTitleDN.setObjectName("lblTitleDN")
        self.grpDangNhap = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.grpDangNhap.setGeometry(QtCore.QRect(10, 120, 581, 371))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.grpDangNhap.setFont(font)
        self.grpDangNhap.setObjectName("grpDangNhap")
        self.lblTaiKhoan = QtWidgets.QLabel(parent=self.grpDangNhap)
        self.lblTaiKhoan.setGeometry(QtCore.QRect(80, 60, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lblTaiKhoan.setFont(font)
        self.lblTaiKhoan.setObjectName("lblTaiKhoan")
        self.lblMatKhau = QtWidgets.QLabel(parent=self.grpDangNhap)
        self.lblMatKhau.setGeometry(QtCore.QRect(80, 120, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lblMatKhau.setFont(font)
        self.lblMatKhau.setObjectName("lblMatKhau")
        self.txtTaiKhoan = QtWidgets.QLineEdit(parent=self.grpDangNhap)
        self.txtTaiKhoan.setGeometry(QtCore.QRect(170, 60, 320, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.txtTaiKhoan.setFont(font)
        self.txtTaiKhoan.setObjectName("txtTaiKhoan")
        self.txtMatKhau = QtWidgets.QLineEdit(parent=self.grpDangNhap)
        self.txtMatKhau.setGeometry(QtCore.QRect(170, 120, 320, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.txtMatKhau.setFont(font)
        self.txtMatKhau.setObjectName("txtMatKhau")
        self.btnDangNhap = QtWidgets.QPushButton(parent=self.grpDangNhap)
        self.btnDangNhap.setGeometry(QtCore.QRect(170, 260, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.btnDangNhap.setFont(font)
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.btnHuy = QtWidgets.QPushButton(parent=self.grpDangNhap)
        self.btnHuy.setGeometry(QtCore.QRect(320, 260, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.btnHuy.setFont(font)
        self.btnHuy.setObjectName("btnHuy")
        self.chkHienMK = QtWidgets.QCheckBox(parent=self.grpDangNhap)
        self.chkHienMK.setGeometry(QtCore.QRect(170, 180, 200, 20))
        self.chkHienMK.setObjectName("chkHienMK")
        formDangNhap.setCentralWidget(self.centralwidget)

        self.retranslateUi(formDangNhap)
        QtCore.QMetaObject.connectSlotsByName(formDangNhap)
        formDangNhap.setTabOrder(self.txtTaiKhoan, self.txtMatKhau)
        formDangNhap.setTabOrder(self.txtMatKhau, self.chkHienMK)
        formDangNhap.setTabOrder(self.chkHienMK, self.btnDangNhap)
        formDangNhap.setTabOrder(self.btnDangNhap, self.btnHuy)

    def retranslateUi(self, formDangNhap):
        _translate = QtCore.QCoreApplication.translate
        formDangNhap.setWindowTitle(_translate("formDangNhap", "Đăng nhập"))
        self.lblTitleDN.setText(_translate("formDangNhap", "Đăng nhập hệ thống"))
        self.grpDangNhap.setTitle(_translate("formDangNhap", "Thông tin đăng nhập"))
        self.lblTaiKhoan.setText(_translate("formDangNhap", "Tài khoản"))
        self.lblMatKhau.setText(_translate("formDangNhap", "Mật khẩu"))
        self.btnDangNhap.setText(_translate("formDangNhap", "Đăng nhập"))
        self.btnHuy.setText(_translate("formDangNhap", "Hủy"))
        self.chkHienMK.setText(_translate("formDangNhap", "Hiển thị mật khẩu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formDangNhap = QtWidgets.QMainWindow()
    ui = Ui_formDangNhap()
    ui.setupUi(formDangNhap)
    formDangNhap.show()
    sys.exit(app.exec())
